# Setup
title:               IFT6758 Blog
tagline:             'An NHL Stats project by Ninaad Kalla and Yosri Ketata'
description:         ''
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ninaad Kalla
  url:               https://github.com/ninkalla
  email:             ninaad.kalla@umontreal.ca

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
