FROM python:3.9-slim

WORKDIR /code

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY serving/ ./serving/

# 4. Expose Streamlit default port
EXPOSE 8501

# 5. Run the dashboard
# We point to serving/dashboard.py because that is where you renamed the file
CMD ["streamlit", "run", "serving/dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]