FROM python:3.11
WORKDIR /code
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY serving/ ./serving/
EXPOSE 8501
CMD ["streamlit", "run", "serving/dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
